ORG 0000H
SETB P0.1   ; SWITCH-1 OFF
SETB P0.2   ; SWITCH-2 OFF
SETB P1.0   ; LED OFF
LOOP: CLR C ; CY=1
ORL C,/P0.2 ; CHECKING P0.2 IS ZERO OR NOT 
ANL C,/P0.1 ;CHECKING P0.1 IS ZERO OR NOT
CPL C       ; COMPLEMENT CY
MOV P1.0,C  ; MOVING CY TO LED
SJMP LOOP   ; CHECKING LOOP AGAIN
END
