ORG 0000H
SETB P0.1   ;  SWITCH-1 OFF
SETB P0.2   ; SWITCH-2 OFF
SETB P1.0   ; LED OFF
AGAIN:CLR C ; RESET CY
MOV C,P0.1  ; MOVING SWITCH-1 LOGIC TO CY
ANL C,P0.2  ; AND CY AND SWITCH-2
MOV P1.0,C  ; MOVING CY TO LED
SJMP AGAIN
END
